### PR TITLE
Make a nice panelset for plots and code

### PR DESCRIPTION
**Pull request by rich-iannone**
This is my attempt to create a panelset display for code and plots (could include other stuff too). I somehow managed to avoid JS with this and doesn't look too bad! 

Fixes: #11 
Fixes: https://github.com/dspatterns/dspatterns/issues/4

### CODE REVIEW

**Comment by rich-iannone** [comment]
The top of Chapter 2 has the prototype for this.

**Comment by apreshill** [comment]
Wow- I cannot believe you did that without JS!

**Comment by rich-iannone** [comment]
I got to this because the JS solution I had didn’t scale well to multiple tabs in a page. But this is something I can use!

**Comment by rich-iannone** [comment]
Okay, this is now done for all plot + code combos in Chapter 2.

**Pull request merged**
